x-defaults: &default-healthcheck
  healthcheck:
    test: ["CMD-SHELL", "curl -f http://localhost:${APP_SERVER_PORT}/actuator/health || exit 1"]
    interval: 10s
    timeout: 5s
    retries: 5

services:
  mongo:
    image: mongo
    container_name: mongo
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: testbase
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_DB_ADMIN_USERNAME: mongo
      MONGO_DB_ADMIN_PASSWORD: mongo
    volumes:
      - mongo:/data/db
    ports:
      - '27017:27017'
    networks:
      - backend
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --port 27017 --quiet
      interval: 3s
      timeout: 5s
      retries: 5

  cloud-config:
    image: magenta/highload/cloud-config:dev
    working_dir: /app
    volumes:
      - ~/.ssh/highload-cloud-config-ro:/root/.ssh/id_rsa:ro
      - ./config:/app/config
    environment:
      SPRING_PROFILES_ACTIVE: standalone,native
    env_file:
      - .env
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8888/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  eureka-server:
    image: magenta/highload/eureka-server:dev
    ports:
      - "8761:8761"
    depends_on:
      cloud-config:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  route:
    image: magenta/highload/route:dev
    ports:
      - '8085:8085'
    depends_on:
      eureka-server:
        condition: service_healthy
    env_file:
      - .env
    <<: *default-healthcheck
    networks:
      - backend

  place:
    image: magenta/highload/place:dev
    ports:
      - '8086:8086'
    depends_on:
      eureka-server:
        condition: service_healthy
    env_file:
      - .env
    <<: *default-healthcheck
    networks:
      - backend

  api-gateway:
    image: magenta/highload/api-gateway:dev
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  authentication:
    image: magenta/highload/authentication:dev
    ports:
      - '8087:8087'
    depends_on:
      eureka-server:
        condition: service_healthy
    env_file:
      - .env
    <<: *default-healthcheck
    networks:
      - backend

  feedback:
    image: magenta/highload/feedback:dev
    ports:
      - '8088:8088'
    depends_on:
      eureka-server:
        condition: service_healthy
    env_file:
      - .env
    <<: *default-healthcheck
    networks:
      - backend

  favorites:
    image: magenta/highload/favorites:dev
    ports:
      - '8089:8089'
    depends_on:
      eureka-server:
        condition: service_healthy
    env_file:
      - .env
    <<: *default-healthcheck
    networks:
      - backend

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8072:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@mongo:27017/testbase?&authSource=admin
      ME_CONFIG_BASICAUTH: false
    healthcheck:
      test: [ "CMD","mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
    tty: true
    stdin_open: true
    networks:
      - backend

volumes:
  mongo:
  
networks:
  backend:
    driver: bridge
