server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: place-service
          uri: lb://PLACE-SERVICE
          predicates:
            - Path=/api/v1/place/**
        - id: route-service
          uri: lb://ROUTE-SERVICE
          predicates:
            - Path=/api/v1/route/**
        - id: feedback-service
          uri: lb://FEEDBACK-SERVICE
          predicates:
            - Path=/api/v1/feedback/**
        - id: favorites-service
          uri: lb://FAVORITES-SERVICE
          predicates:
            - Path=/api/v1/favorites/**
        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/api/v1/auth/**
      discovery:
        locator:
          enabled: true
    loadbalancer:
      retry:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

