spring:
  application:
    name: feedback-service
  data:
    mongodb:
        url: mongodb://mongo:mongo@mongo:27017/testbase?authSource=admin&directConnection=true
        database: testbase
        authentication-database: admin
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: ${APP_SERVER_PORT:8088}
app.base-url: /api/v1

jwt:
  secret:
    sign: ${JWT_SECRET:0LHQvtC20LUg0L/QvtC80L7Qs9C4INC90LDQvCDQt9Cw0LrRgNGL0YLRjCDRjdGC0L7RgiDQv9GA0LXQtNC80LXRgg==}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

